name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Roda diariamente
  workflow_dispatch:     # Permite acionar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: AlexBruno099
          svg_fill: "#8A2BE2"  # Cor roxa para combinar com seu tema
          svg_stroke: "#000000"

      - name: Commit and Push
        run: |
          git config --global user.name "AlexBruno099"
          git config --global user.email "alexbrunorr099@gmail.com"
          git add -A
          git commit -m "Update snake animation"
          git push
